dist: xenial

language: python

python:
  - "3.7"

git:
  depth: false

services:
  - docker

install:
  - pip3 install -r requirements.txt

script:
  - chmod +x ./tools/docker/entrypoint.sh
  - ./tools/docker/entrypoint.sh
