version: '3.4'

services:
  app:
    image: npiontko/sample-node-todo
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=todo
      - PGSERVER=db
      - WAIT_HOSTS=db:5432
    ports:
      - 80:3000
    restart: always
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo
