version: '3.4'

services:
  app.test:
    image: npiontko/sample-node-todo
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=todo
      - PGSERVER=db.test
      - WAIT_HOSTS=db.test:5432
      - PORT=80
    ports:
      - 80:80
    depends_on:
      - db.test

  db.test:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo

  selenium-chrome:
    image: selenium/standalone-chrome
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444
