class WellKnownConfigKeys:
    """
    Well known config keys.
    """
    APP_BASE_URI = 'APP_BASE_URI'
    APP_PROBE_URI = 'APP_PROBE_URI'
    APP_DOCKER_COMPOSE_FILE = 'APP_DOCKER_COMPOSE_FILE'
    SELENIUM_REMOTE = 'SELENIUM_REMOTE'
    SELENIUM_REMOTE_URI = 'SELENIUM_REMOTE_URI'
    SELENIUM_DRIVER = 'SELENIUM_DRIVER'
    ARTIFACTS_DIR = 'ARTIFACTS_DIR'
    WAIT_TIMEOUT = 'WAIT_TIMEOUT'
